description: |
  Get an existing match by its bancho channel id.
operationId: getMatch

parameters:
  - in: path
    name: gameMatchId
    schema:
      type: integer
    required: true
    description: The bancho ID of the match to get.

responses:
  200:
    content:
      application/json:
        schema:
          properties:
            endsAt:
              example: 2025-08-24T13:07:27
              format: date-time
              nullable: true
              type: string
            gameMatchId:
              example: 119065801
              type: integer
            name:
              example: "MWC4K2025 RO32: Philippines VS France"
              type: string
          type: object
    description: Match related data.
  400:
    content:
      application/json:
        schema:
          properties:
            instance:
              example: /api/v1/matches/random-string
              type: string
            status:
              example: 400
              type: integer
            title:
              example: Bad Request
              type: string
            detail:
              example: Input validation failed
              type: string
            errors:
              items:
                properties:
                  path:
                    example: /params/gameMatchId
                    type: string
                  message:
                    example: gameMatchId must be a positive integer string
                    type: string
                  errorCode:
                    example: validator.getMatchParametersValidator.gameMatchId.integer
                    type: string
          type: object
    description: Missing or invalid gameMatchId.
  401:
    content:
      application/json:
        schema:
          properties:
            instance:
              example: /api/v1/matches/119065801
              type: string
            status:
              example: 401
              type: integer
            title:
              example: Unauthorized
              type: string
            detail:
              example: You must be authenticated to access this resource.
              type: string
          type: object
    description: Missing or invalid authentication.

security:
  - cookie: []
summary: Get an existing match.
tags:
  -  Matches
