description: |
  Closes an existing match. This will also ask bancho to close the multiplayer channel
  associated with it.
operationId: closeMatch

parameters:
  - in: path
    name: gameMatchId
    schema:
      type: integer
    required: true
    description: The bancho ID of the match to close.

responses:
  200:
    content:
      application/json:
        schema:
          properties:
            status:
              example: closed
              type: string
          type: object
    description: Match and bancho channel closed.
  400:
    content:
      application/json:
        schema:
          properties:
            instance:
              example: /api/v1/matches/random-string/close
              type: string
            status:
              example: 400
              type: integer
            title:
              example: Bad Request
              type: string
            detail:
              example: Input validation failed
              type: string
            errors:
              items:
                properties:
                  path:
                    example: /params/id
                    type: string
                  message:
                    example: gameMatchId must be a positive integer string
                    type: string
                  errorCode:
                    example: validator.closeMatchParametersValidator.gameMatchId.integer
                    type: string
          type: object
    description: Missing or invalid id.
  401:
    content:
      application/json:
        schema:
          properties:
            instance:
              example: /api/v1/matches/119065801/close
              type: string
            status:
              example: 401
              type: integer
            title:
              example: Unauthorized
              type: string
            detail:
              example: You must be authenticated to access this resource.
              type: string
          type: object
    description: Missing or invalid authentication.

security:
  - cookie: []
summary: Close an existing match.
tags:
  -  Matches
